import fs from "node:fs";
import crypto from "node:crypto";
const hash = path => crypto.createHash("sha256").update(fs.readFileSync(path)).digest("hex").toUpperCase();
const exit = JSON.parse(fs.readFileSync("progress/weekly_review_replay_exit.json", "utf8"));
const before = JSON.parse(fs.readFileSync("progress/weekly_review_replay_before.json", "utf8"));
const after = {capturedAt:new Date().toISOString(),files:before.files.map(({path})=>({path,sha256:hash(path)}))};
const differences = after.files.filter((f,i)=>f.sha256!==before.files[i].sha256);
fs.writeFileSync("progress/weekly_review_replay_after.json",JSON.stringify({...after,differences},null,2)+"\n");
const rawPath="frontend/reports/mutation-weekly-review-replay/mutation.json";
const preserved="progress/weekly_review_stryker_replay.json";
if(fs.existsSync(preserved)) throw new Error("Preserved replay already exists");
fs.copyFileSync(rawPath,preserved);
const report=JSON.parse(fs.readFileSync(preserved,"utf8"));
const proposal=JSON.parse(fs.readFileSync("progress/weekly_review_refined_replay_proposal.json","utf8"));
if(hash("progress/weekly_review_stryker_original.json")!==proposal.originalRawSha256) throw new Error("Original changed");
const all=Object.entries(report.files).flatMap(([file,value])=>value.mutants.map(m=>({file,...m})));
const signature = m => JSON.stringify([m.file,m.location.start.line,m.location.start.column,m.location.end.line,m.location.end.column,m.mutatorName,m.replacement]);
const mapping=proposal.signatures.map(original=>{
 const matches=all.filter(m=>signature(m)===signature(original));
 if(matches.length!==1)throw new Error(`Signature ${original.id}: ${matches.length} matches`);
 return {originalId:original.id,...matches[0]};
});
const mapped=new Set(mapping.map(m=>signature(m)));
const extras=all.filter(m=>!mapped.has(signature(m)));
const counts=items=>items.reduce((out,m)=>(out[m.status]=(out[m.status]??0)+1,out),{});
const byFile=Object.fromEntries(Object.keys(report.files).map(file=>[file,counts(all.filter(m=>m.file===file))]));
const result={...exit,rawSha256:hash(preserved),inputs:after.files.length,differences,total:all.length,counts:counts(all),byFile,targetCounts:counts(mapping),extraCounts:counts(extras),mapping,extras};
fs.writeFileSync("progress/weekly_review_replay_mapping.json",JSON.stringify(result,null,2)+"\n");
console.log(JSON.stringify({exitCode:exit.exitCode,total:all.length,counts:result.counts,targetCounts:result.targetCounts,extraCounts:result.extraCounts,differences,rawSha256:result.rawSha256}));
